name: Montar mi pagina a Github

on:
  push:
    branches:
      - main

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Clonar repositorio
        uses: actions/checkout@v3

      - name: Configurar GitHub Pages
        uses: actions/configure-pages@v3

      - name: Subir artefactos para GitHub Pages
        uses: actions/upload-pages-artifact@v1
        with:
          path: '.'  # Aquí se sube la raíz con index.html y estilos

  deploy:
    needs: build-and-deploy
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deploy-pages.outputs.page_url }}
    steps:
      - name: Desplegar sitio
        id: deploy-pages
        uses: actions/deploy-pages@v1
